### PR TITLE
make 2htdp/image usable within sandbox

### PR DESCRIPTION
**Pull request by sorawee**
Calling `get-preference*` will attempt to read `org.racket-lang.prefs.rktd` or `racket-prefs.rktd` which might not be granted the read access within a sandbox, resulting in the error:

  file-or-directory-modify-seconds: `read' access denied for ....

This commit catches the error if this situation happens and default back to the default value.

### CODE REVIEW

**Comment by samth** [comment]
Making `default-size` a thunk seems like it would also help here.

**Comment by sorawee** [comment]
We can `delay` it, but the exception catching is still needed, since it might eventually get forced anyway, right?

**Comment by samth** [comment]
Yes, I think catching the exception is still a good idea; just worth avoiding doing the whole thing at all when not needed.

**Comment by sorawee** [comment]
Done!

**Comment by sorawee** [comment]
@samth @mflatt @rfindler OK to merge?

**Comment by samth** [comment]
LGTM

**Pull request merged**
